### ISSUE TITLE
Warning C++ standard

### ISSUE THREAD

**Issue by Frustramatic** [golemfactory/homebrew-golem#6]
Warning: golemfactory/golem/golem dependency golemfactory/hyperg/hyperg was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.

**Comment by gborowik** [comment]
Please keep in mind that Golem depends on many packages. Therefore, the installation varies on the computer. The problem was due to the incompatibility of Xcode and go-ethereum. During the installation with Homebrew, the go-ethereum is compiled using Xcode that you have on your computer. Unfortunately, the last patch has caused problems. We fixed it today.
